/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.energygreen.mavenproject;

import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author vitor
 */

public class telaConsulta extends javax.swing.JFrame {
    
    DefaultTableModel copiaResult;
    
    public telaConsulta() throws SQLException {
        initComponents();
        
        setLocationRelativeTo(null);
        
        DataInfo dataInfo = DataInfo.getInstance();
        String cpf = dataInfo.getUsuarioLogado().getCpf();
        
        String url = "jdbc:mysql://localhost:3306/energygreen";
        String dbUsername = "root";
        String dbPassword = "m6230ghz";
        String sql = "SELECT id, kwh, mes, regiao, contaBruta, contaDesconto, economia FROM registro WHERE cpf = ?";

        try (Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);
        PreparedStatement statement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {
        statement.setString(1, cpf);
    
        ResultSet resultSet = statement.executeQuery();
        
        // Obter o número de colunas no ResultSet
            int numColumns = resultSet.getMetaData().getColumnCount();

            // Contar o número de linhas no ResultSet
            int numLinhas = 0;
            if (resultSet.last()) {
                numLinhas = resultSet.getRow();
                resultSet.beforeFirst();
            }
        
        Object[][] data = new Object[numLinhas][numColumns];
        
        
            // Preencher o array com os dados do ResultSet
            int linha = 0;
            while (resultSet.next()) {
                for (int coluna = 0; coluna < numColumns; coluna++) {
                    data[linha][coluna] = resultSet.getObject(coluna + 1);
                }
                linha++;
            }
            
            Object[] nomColunas = {"Id","Kwh", "Data", "Região", "Valor Bruto", "Conta Desconto", "Economia"};
            
            DefaultTableModel model = new DefaultTableModel(data, nomColunas);
            copiaResult = model;
            jTable1.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtAnoFim = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAnoIn = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxMesIn = new javax.swing.JComboBox<>();
        cbxMesFim = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Consulta");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtAnoFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFimActionPerformed(evt);
            }
        });

        jLabel7.setText("Insira período final");

        txtAnoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoInActionPerformed(evt);
            }
        });

        jLabel6.setText("Insira período inicial");

        cbxMesIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cbxMesIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesInActionPerformed(evt);
            }
        });

        cbxMesFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Mostrar Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deletar Registro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ano");

        jLabel2.setText("Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbxMesIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAnoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxMesIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new telaMenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAnoFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFimActionPerformed

    private void txtAnoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoInActionPerformed

    private void cbxMesInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesInActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DataInfo dataInfo = DataInfo.getInstance();
        String cpf = dataInfo.getUsuarioLogado().getCpf();
        
        String url = "jdbc:mysql://localhost:3306/energygreen";
        String dbUsername = "root";
        String dbPassword = "m6230ghz";
        String sql = "SELECT id, kwh, mes, regiao, contaBruta, contaDesconto, economia FROM registro WHERE cpf = ?";

        try {
            Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);
            PreparedStatement statement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            statement.setString(1, cpf);
    
        ResultSet resultSet = statement.executeQuery();
        
        // Obter o número de colunas no ResultSet
            int numColumns = resultSet.getMetaData().getColumnCount();

            // Contar o número de linhas no ResultSet
            int numLinhas = 0;
            if (resultSet.last()) {
                numLinhas = resultSet.getRow();
                resultSet.beforeFirst();
            }
        
        Object[][] data = new Object[numLinhas][numColumns];
        
        
            // Preencher o array com os dados do ResultSet
            int linha = 0;
            while (resultSet.next()) {
                for (int coluna = 0; coluna < numColumns; coluna++) {
                    data[linha][coluna] = resultSet.getObject(coluna + 1);
                }
                linha++;
            }
            
            Object[] nomColunas = {"Id", "Kwh", "Data", "Região", "Valor Bruto", "Conta Desconto", "Economia"};
            
            DefaultTableModel model = new DefaultTableModel(data, nomColunas);
            copiaResult = model;
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(telaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        if (cbxMesIn.getSelectedIndex()== 0 ) {
        JOptionPane.showMessageDialog(null, "Selecione o mês fnicial.");
        return; // Encerrar o método sem continuar o cálculo
        }
        
        if (cbxMesFim.getSelectedIndex()== 0 ) {
        JOptionPane.showMessageDialog(null, "Selecione o mês final.");
        return; // Encerrar o método sem continuar o cálculo
        }
        
         if (txtAnoIn.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Selecione o ano inicial.");
        return; // Encerrar o método sem continuar o cálculo
        }
         
        if (txtAnoFim.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Selecione o ano final.");
        return; // Encerrar o método sem continuar o cálculo
        }
        
        DataInfo dataInfo = DataInfo.getInstance();
        String cpf = dataInfo.getUsuarioLogado().getCpf();
        Date dtInicial = Date.valueOf(txtAnoIn.getText()+ "-" + cbxMesIn.getSelectedIndex() + "-01");
        Date dtFinal = Date.valueOf(txtAnoFim.getText()+ "-" + cbxMesFim.getSelectedIndex() + "-01");
        
        String url = "jdbc:mysql://localhost:3306/energygreen";
        String dbUsername = "root";
        String dbPassword = "m6230ghz";
        String sql = "SELECT id, kwh, mes, regiao, contaBruta, contaDesconto, economia FROM registro WHERE cpf = ? AND mes >= ? AND mes <= ?";

        try {
            Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);
            PreparedStatement statement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            statement.setString(1, cpf);
            statement.setDate(2, dtInicial);
            statement.setDate(3, dtFinal);
    
            ResultSet resultSet = statement.executeQuery();
        
            // Obter o número de colunas no ResultSet
            int numColumns = resultSet.getMetaData().getColumnCount();

            // Contar o número de linhas no ResultSet
            int numLinhas = 0;
            if (resultSet.last()) {
                numLinhas = resultSet.getRow();
                resultSet.beforeFirst();
            }
        
            Object[][] data = new Object[numLinhas][numColumns];
        
            // Preencher o array com os dados do ResultSet
            int linha = 0;
            while (resultSet.next()) {
                for (int coluna = 0; coluna < numColumns; coluna++) {
                    data[linha][coluna] = resultSet.getObject(coluna + 1);
                }
                linha++;
            }
            
            Object[] nomColunas = {"Id" ,"Kwh", "Data", "Região", "Valor Bruto", "Conta Desconto", "Economia"};
            
            DefaultTableModel model = new DefaultTableModel(data, nomColunas);
            jTable1.setModel(model);
        } catch (Exception ex) {
            
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = jTable1.getSelectedRow();
        
        if(linhaSelecionada != -1){                  
           int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o item?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
           if (resposta == JOptionPane.YES_OPTION) { 
            try {
                int id = (int) jTable1.getValueAt(linhaSelecionada, 0);
                String url = "jdbc:mysql://localhost:3306/energygreen";
                String dbUsername = "root";
                String dbPassword = "m6230ghz";
                String sql = ("DELETE FROM registro WHERE id = ?");
            
                Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);
                PreparedStatement statement = connection.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                statement.setInt(1, id);
    
                statement.executeUpdate();
                MyTableModel model = new MyTableModel((DefaultTableModel)jTable1.getModel());
                model.removeRow(linhaSelecionada);
                                
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new telaConsulta().setVisible(true);
                } catch (SQLException ex) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxMesFim;
    private javax.swing.JComboBox<String> cbxMesIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField txtAnoFim;
    private javax.swing.JFormattedTextField txtAnoIn;
    // End of variables declaration//GEN-END:variables

}
